// grub_bootstrap.go - the GRUB configuration for a bootstrap image.
//
// A bootstrap image is the "empty" image shipped before the model and DSM
// version have been decided. On boot, vibeldr-boot brings up its TUI, the user
// picks a model and a DSM, and it then downloads, decrypts, patches, rewrites
// the partitions and reboots into DSM. The kernel and initrd GRUB loads here
// both sit on P1 (the boot FAT) under their own names.
//
// grub_bootstrap.go - 부트스트랩 이미지의 GRUB 설정.
//
// 부트스트랩 이미지는 모델/DSM 이 아직 결정되지 않은 상태에서 배포되는
// "빈" 이미지다. 부팅되면 vibeldr-boot 이 TUI 를 띄워 사용자가 모델과
// DSM 을 고르고, 다운로드·복호화·패치·파티션 재작성을 마친 다음 리부트로
// DSM 으로 넘어간다. 여기서 GRUB 이 로드하는 커널·initrd 는 모두 P1
// (부트 FAT) 안에 자기 이름 그대로 놓여 있다.

package image

import (
	"fmt"
	"strings"
)

// The names of the two files GRUB looks for on a bootstrap image's P1.
//
// They are constants so that grub.cfg and the actual file placement cannot be
// hard-coded separately in two places and drift subtly apart - vmlinuz against
// vmlinuz-lts, for instance.
//
// 부트스트랩 이미지 P1 안에서 GRUB 이 찾는 두 파일의 이름.
//
// 이름을 상수로 고정하는 이유는 grub.cfg 와 실제 파일 배치가 두 곳에서
// 각자 하드코딩되어 미묘하게 어긋나는 상황 (예: `vmlinuz` 와
// `vmlinuz-lts` 오탈자) 을 원천 차단하기 위해서다.
const (
	BootstrapKernelName = "vmlinuz"
	BootstrapInitrdName = "initrd-vibeldr"
)

// BootstrapEntryID is the GRUB menu entry id used to name the default boot
// target.
//
// BootstrapEntryID - GRUB 메뉴엔트리 id. 기본 부팅 대상을 이 id 로 지정한다.
const BootstrapEntryID = "build"

// BootstrapGfxMode is the list of graphics modes handed to GRUB; the first one
// this machine accepts is used.
//
// 1024x768 comes first because the install screen's layout is designed around
// that size. A larger screen only stretches the layout, but below 800x600 the
// lists start getting cut off. auto is the last resort.
//
// BootstrapGfxMode - GRUB 에 넘길 그래픽 모드 후보. 앞에서부터 이 기계가
// 받아주는 첫 모드가 쓰인다.
//
// 1024x768 을 먼저 두는 이유는 설치 화면의 배치가 그 크기를 기준으로
// 잡혀 있어서다. 더 큰 화면에서도 배치는 늘어날 뿐 깨지지 않지만,
// 800x600 보다 작아지면 목록이 잘린다. auto 는 마지막 안전망이다.
const BootstrapGfxMode = "1024x768x32,1024x768,1280x1024x32,1280x1024,800x600x32,800x600,auto"

// BootstrapGrubConfig is the content of boot/grub/grub.cfg on a bootstrap
// image's P1.
//
// There is no microcode option: a bootstrap lives briefly, and vibeldr-boot
// assembles the real DSM image and reboots, so early microcode is handled in
// that result. Here the minimum that reliably loads a kernel and an initrd is
// better.
//
// Serial console: a headless VM is a common case, so GRUB is told to use the
// serial port for input and output too. If that fails - no serial hardware, or
// a GRUB module missing - it is passed over quietly and the console boot
// continues.
//
// Graphics mode: vibeldr-boot's install screen draws directly on the
// framebuffer. For the kernel to have a framebuffer, somebody has to set a
// graphics mode first, and that somebody is GRUB. all_video loads every video
// driver this machine can use, a mode is set, and gfxpayload=keep hands that
// mode straight to the kernel, which takes it as efifb (UEFI) or vesafb (BIOS)
// and creates /dev/fb0. If setting the mode fails there is simply no
// framebuffer, and the text-only screen takes over.
//
// BootstrapGrubConfig - 부트스트랩 이미지 P1 의 boot/grub/grub.cfg 내용.
//
// 마이크로코드 옵션이 없다. 부트스트랩은 짧게 살고 vibeldr-boot 이 실제
// DSM 이미지를 새로 조립해 리부트하므로, 조기 마이크로코드는 그 조립
// 결과에서 챙기면 된다. 여기서는 커널·initrd 두 개만 확실히 로드하는
// 최소 설정이 낫다.
//
// 시리얼 콘솔 지원: 헤드리스 VM 이 흔한 시나리오이므로 GRUB 이 시리얼도
// 입력·출력으로 삼도록 한다. 실패하면 (시리얼 하드웨어가 없거나 GRUB
// 모듈이 부족하면) 조용히 넘어가고 콘솔 부팅은 계속된다.
//
// 그래픽 모드: vibeldr-boot 의 설치 화면은 프레임버퍼에 직접 그린다.
// 커널이 프레임버퍼를 가지려면 그 전에 누군가 그래픽 모드를 켜 둬야
// 하는데, 그 일을 GRUB 이 한다. all_video 로 이 기계에서 쓸 수 있는
// 비디오 드라이버를 전부 올리고, 모드를 세운 뒤 gfxpayload=keep 으로
// 그 모드를 그대로 커널에 넘긴다. 커널은 이것을 efifb (UEFI) 나
// vesafb (BIOS) 로 받아 /dev/fb0 을 만든다. 모드 설정이 실패하면
// 프레임버퍼가 없을 뿐이고, 그때는 글자만 쓰는 화면으로 넘어간다.
func BootstrapGrubConfig() []byte {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# Generated by vibeldr bootstrap - do not edit.")
	w("# 부트스트랩 이미지: 제네릭 커널 + vibeldr-boot 만.")
	w("set default=%s", BootstrapEntryID)
	w("set timeout=3")
	w("")
	w("insmod part_msdos")
	w("insmod fat")
	w("insmod search_label")
	w("insmod all_video")
	w("insmod gfxterm")
	w("")
	// Use the first mode in the list this machine accepts. auto is last, so
	// that GRUB chooses for itself when none of them work.
	//
	// 목록의 앞에서부터 이 기계가 받아주는 첫 모드를 쓴다. auto 를 끝에
	// 둬서 어느 것도 안 되면 GRUB 이 알아서 고르게 한다.
	w("set gfxmode=%s", BootstrapGfxMode)
	w("set gfxpayload=keep")
	w("terminal_output --append gfxterm")
	w("")
	w("if serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1; then")
	w("  terminal_input --append serial")
	w("  terminal_output --append serial")
	w("fi")
	w("")
	// The kernel and the initrd are on this partition, the boot FAT. There is
	// no need to set root here: before this file is read, the configuration
	// built into core.img (or the EFI stub) has already searched for the
	// VIBELDR1 label and set root to that partition, so /vmlinuz and
	// /initrd-vibeldr open as they are.
	//
	// 커널과 initrd 는 이 파티션 (부트 FAT) 에 있다. 여기서 root 를 다시
	// 지정할 필요는 없다. 이 파일을 읽기 전에 core.img 에 내장된 설정 (또는
	// EFI 스텁) 이 VIBELDR1 라벨을 찾아 root 를 그 파티션으로 잡아 두었으므로
	// /vmlinuz, /initrd-vibeldr 경로가 그대로 열린다.
	w("menuentry 'vibeldr - configure and install' --id %s {", BootstrapEntryID)
	w("  echo 'Loading generic kernel...'")
	w("  linux /%s console=ttyS0,115200n8 console=tty0 loglevel=4 panic=5",
		BootstrapKernelName)
	w("  echo 'Loading vibeldr-boot...'")
	w("  initrd /%s", BootstrapInitrdName)
	w("}")
	w("")
	return []byte(b.String())
}
